name: Update rok CLI
description: Updates the formula for the Immerok Cloud CLI.
inputs:
  gitTag:
    description: git tag to release ("rok/v0.0.1" or "rok/v0.0.1-test").
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update version
      working-directory: configs
      shell: bash
      run: |
        version="$(echo "${{ inputs.gitTag }}" | cut -c 6-)"
        yq -i ".version = \"${version}\"" "rok.yaml"

    - name: Update checksums
      working-directory: configs
      shell: bash
      run: |
        for os in darwin linux; do
          for arch in amd64 arm64; do
            checksum="$(curl -sL "https://releases.immerok.cloud/${{ inputs.gitTag }}/rok-${os}-${arch}.tar.gz" | shasum -a 256 | cut -d ' ' -f 1)"
            yq -i ".sha256[\"${os}\"][\"${arch}\"] = \"${checksum}\"" "rok.yaml"
          done
        done

    - name: Commit
      working-directory: configs
      shell: bash
      run: |
        git config --global user.email "<noreply@github.com>"
        git config --global user.name "GitHub"

        git --no-pager diff
        git commit -am "release ${{ inputs.gitTag }}" --author "Immerok <Immerok>"

    - name: Push
      shell: bash
      working-directory: configs
      run: |
        git push
