name: Update rok CLI
on:
  repository_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update rok CLI
        uses: ./.github/workflows/composite/update_rok
        with:
          gitTag: ${{ github.event.client_payload.gitTag }}
          dry: false
