name: Update rok CLI
on:
  repository_dispatch:
    types: [release]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update rok CLI
        uses: ./.github/workflows/composite/update_rok
        with:
          gitTag: ${{ github.event.client_payload.gitTag }}
